[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]
